server:
  port: 8081

spring:
  application:
    name: huashui-auth

  profiles:
    active: dev

  cloud:
    nacos:
      server-addr: 43.143.130.165:8848
      username: nacos
      password: nacos

      config:
        namespace: 02c193c2-fbeb-4fe9-9196-2e55de4730c8
        group: DEFAULT_GROUP
        file-extension: yaml

      discovery:
        namespace: 02c193c2-fbeb-4fe9-9196-2e55de4730c8

  config:
    import:
      - optional:nacos:shared-spring.yaml
      - optional:nacos:shared-redis.yaml
      - optional:nacos:shared-mybatis.yaml
      - optional:nacos:shared-logs.yaml
      - optional:nacos:shared-feign.yaml
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}

sa-token:
  token-name: Authorization
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: tik
  is-log: false

hs:
  swagger:
    enable: true
    enableResponseWrap: true
    package-path: com.huashui.auth.controller
    title: 华水校园生活 - 认证中心接口文档
    description: 该服务包含登录、注册、认证功能
    contact-name: 华北水利水电大学.信息工程学院
    version: v1.0

  jdbc:
    database: huashui_campus_life

  auth:
    resource:
      enable: true