server:
  port: 8080

spring:
  application:
    name: huashui-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: ${NACOS_NAMESPACE:}
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
    gateway:
      routes:
        # Auth
        - id: huashui-auth
          uri: lb://huashui-auth
          predicates:
            - Path=/auth/**
        # User
        - id: huashui-user
          uri: lb://huashui-user
          predicates:
            - Path=/user/**
        # Dormitory
        - id: huashui-dormitory
          uri: lb://huashui-dormitory
          predicates:
            - Path=/dormitory/**
        # Utility
        - id: huashui-utility
          uri: lb://huashui-utility
          predicates:
            - Path=/utility/**
        # Attendance
        - id: huashui-attendance
          uri: lb://huashui-attendance
          predicates:
            - Path=/attendance/**
        # File
        - id: huashui-file
          uri: lb://huashui-file
          predicates:
            - Path=/file/**
        # System
        - id: huashui-system
          uri: lb://huashui-system
          predicates:
            - Path=/system/**

############## Sa-Token ##############
sa-token:
  token-name: Authorization
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: tik
  is-log: false

logging:
  level:
    com.huashui.gateway: debug
