server:
  port: 8080

spring:
  web-application-type: reactive
  main:
    allow-bean-definition-overriding: true
  application:
    name: huashui-gateway

  profiles:
    active: dev

  cloud:
    nacos:
      server-addr: 43.143.130.165:8848
      username: nacos
      password: nacos

      config:
        namespace: 02c193c2-fbeb-4fe9-9196-2e55de4730c8
        group: DEFAULT_GROUP
        file-extension: yaml

      discovery:
        namespace: 02c193c2-fbeb-4fe9-9196-2e55de4730c8

    gateway:
      routes:
        - id: huashui-auth
          uri: lb://huashui-auth
          predicates:
            - Path=/auth/**
        - id: huashui-user
          uri: lb://huashui-user
          predicates:
            - Path=/user/**
        - id: huashui-dormitory
          uri: lb://huashui-dormitory
          predicates:
            - Path=/dormitory/**
        - id: huashui-utility
          uri: lb://huashui-utility
          predicates:
            - Path=/utility/**
        - id: huashui-attendance
          uri: lb://huashui-attendance
          predicates:
            - Path=/attendance/**
        - id: huashui-file
          uri: lb://huashui-file
          predicates:
            - Path=/file/**
        - id: huashui-system
          uri: lb://huashui-system
          predicates:
            - Path=/system/**

  config:
    import:
      - optional:nacos:shared-spring.yaml
      - optional:nacos:shared-redis.yaml
      - optional:nacos:shared-logs.yaml
      - optional:nacos:shared-gateway.yaml
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}

sa-token:
  token-name: Authorization
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: tik
  is-log: false

hs:
  auth:
    resource:
      enable: true